# Generated by Django 4.1.3 on 2022-12-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Date create'),
        ),
    ]
