# Generated by Django 4.1.3 on 2022-12-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0002_alter_entry_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_media.entry', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'profileimage',
                'verbose_name_plural': 'profileimages',
            },
        ),
    ]
