# Generated by Django 4.1.3 on 2022-12-05 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_media', '0004_alter_profileimage_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cover name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date create')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'cover',
                'verbose_name_plural': 'covers',
            },
        ),
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_media.cover', verbose_name='Cover')),
            ],
            options={
                'verbose_name': 'cover image',
                'verbose_name_plural': 'cover images',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Music name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date create')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'music',
                'verbose_name_plural': 'musics',
            },
        ),
        migrations.CreateModel(
            name='MusicSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='musics/')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_media.cover', verbose_name='Cover')),
            ],
            options={
                'verbose_name': 'music sound',
                'verbose_name_plural': 'music sounds',
            },
        ),
        migrations.CreateModel(
            name='MusicText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Text name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date create')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'music text',
                'verbose_name_plural': 'music texts',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.RemoveField(
            model_name='entryimage',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='EntryImage',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_media.status', verbose_name='Status'),
            preserve_default=False,
        ),
    ]
